<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-LEC46EMO" failures="2" tests="5" name="com.test.RegisterPageTest" time="71.821" errors="0" timestamp="2025-03-27T13:12:07 IST" skipped="0">
  <testcase classname="com.test.RegisterPageTest" name="verifyRegisterPageNavigation1" time="15.982">
    <failure message="expected [Your registration completed] but found [The specified email already exists
Your Personal Details
Gender: Male Female
First name: *
Last name: *
Email: *
Your Password
Password: *
Confirm password: *]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Your registration completed] but found [The specified email already exists
Your Personal Details
Gender: Male Female
First name: *
Last name: *
Email: *
Your Password
Password: *
Confirm password: *]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.test.RegisterPageTest.verifyRegisterPageNavigation1(RegisterPageTest.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- verifyRegisterPageNavigation1 -->
  <testcase classname="com.test.RegisterPageTest" name="verifyRegisterPageNavigation1" time="16.003"/>
  <testcase classname="com.test.RegisterPageTest" name="verifyRegisterPageNavigation" time="13.087"/>
  <testcase classname="com.test.RegisterPageTest" name="verifyRegisterPageNavigation1" time="11.155"/>
  <testcase classname="com.test.RegisterPageTest" name="verifyRegisterPageNavigation1" time="15.594">
    <failure message="expected [Your registration completed] but found [The specified email already exists
Your Personal Details
Gender: Male Female
First name: *
Last name: *
Email: *
Your Password
Password: *
Confirm password: *]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Your registration completed] but found [The specified email already exists
Your Personal Details
Gender: Male Female
First name: *
Last name: *
Email: *
Your Password
Password: *
Confirm password: *]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.test.RegisterPageTest.verifyRegisterPageNavigation1(RegisterPageTest.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
]]>
    </failure>
  </testcase> <!-- verifyRegisterPageNavigation1 -->
</testsuite> <!-- com.test.RegisterPageTest -->
